language: android
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^v.*$/

env:
  global:
    - TERM=dumb
    - DX_HEAP_SIZE=1536
    - ANDROID_API=29
    - EMULATOR_API=24
    - ANDROID_BUILD_TOOLS=29.0.2
    - ADB_INSTALL_TIMEOUT=5
    - secure: "WmEW+bjdOo9JAfNPnsnRCuCNJJ0wAiKKCnaZw4+MN15vlnR5ORbNIZcRuxmZJ3CIOCj09xFXehjRvm2adVazle02ZNRN89tXsuLnfBiSh64Cc7H9soVAopXlmOJSq5vM46GebHvgoBgq3PZyt2LSMx0GccN1N4QNkxKgkIqLIMHur5zixwyBGcoIRGLGgBOpUo/RXdMZF1qztqKwaD2iOoZecfCjLL2Ukv68f7JTZdnONTVqs3AAHkZmiYibIbQoJCm9zAQjhq2QxVTG0UGGMEjMth/D87LMNwxvaeAWxugM6oFsNm24BvlYykGDgm/GpZx3DFZ2UKgJSjiKWxrs9wfgpuBC0dhRVotkSLXQsoykaGI1VGE01z6zSOpeJxaptyaFOZOvo3BpPc4uSLcNj/hBeIn6s8CuRJMiiZsZRnrHe54//ZEeXX9HcweRYr7z65ka5az5ODIEuHI7Mop+cvSTt93Ne2Gg3QtxBDRM0ZVZe7/0AOFZgPCj3EDizvV8ob8KyqbXglbQpBCjtZLnLRif530Tbphv137KRY7jN3im3GPJfG3v5JiFGN7alxyax1OJSeeEWwmPSe1bMHi7v4tuKT4WUC7UCRpqy5naUtLo0FyMsVmJvI/VFYurtUUZynB7Dy3aJZYvkjIiVoSS64PqtVVXlvA95MVAQTGtjBI="
    - secure: "XYQxZIb80PIa8N9lJHcT532H2bZ0mCpahe/WCO/gJvmVXQOcFwm0JVbjD1x9Gr+OOGZcY336f7NgFoAJjehxwx7HV6JwpVQk1PH9AXvMZa394o9Ea38heDiWWcsEXoBGTEPgNn2yIGRxcyuHUEVOLftmtnwrDfJV/9CUkofFc0I7gsBZIRRp7WtADEkZLn8DdSMLmhoOjoWEBHxWlpcLCo9AM85QeWrg5gxrCl76fllzKWef7P5SchT+IWeqI7ssiT0twufKhjJQyGrdTZh1e5dheR/ts2qR0IUBd4YF6Zxc7Er//J8DPeN1J4cyymTfim5uxib5PtOK0kj26vkW18n0vEIXfkelgPKsCimGcgI9JKNuEkfJfcAVQgTqEhQQWufaVkU/VRbPN0xpEdOVCqfOuugqfMv70Tmc47xK5Qrw607XOW7o3xoqsKeFwDM60LmqFYlF7xm3WZYpojAT6wnTy53F/2VyVma1jIBlKwBzrOLREkXtrBVwWvf/9/tg2zuSEBOzz0yxNFHycOQNVWiVHlBu1vLwfB9fc5QXOGBSbq1OOM9jjKHHxQ/KcLW0Ev3rqK14mFiMM8whvHY2SuzQ/HtoKOK26Cv7XXnVqe20ZdeNI63Ko/JC9JR1II1gKMqGSrbzl/fEBPc5eyYvadxKB00NSa+WFirj6erzu08="

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon/
    - $HOME/.android/build-cache/

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API
  - extra
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$ANDROID_API

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - "export TRAVIS_LAST_COMMIT_MSG=\"$(git log --format=%s --no-merges -n 1)\""
  - source version.properties
  - export MAJOR MINOR PATCH

# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true  # if we don't skip install, ./gradlew assemble is invoked, but this task is not available.

before_script:
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH  # ensure our tools are prefered over included ones.
  - export ARTIFACTORY_DEPLOY="true"

script:
  - ./gradlew ktlintCheck
  - ./gradlew detekt
  - ./gradlew build

deploy:
  - provider: script
    script: scripts/bintrayUpload.sh
    skip_cleanup: true
    on:
      tags: true

after_deploy:
  - ./gradlew createTweet
